name: "sample-application"

on:
  push:
    branches:
      - "main"
  
  pull_request:
        branches:
         - "main"


jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - name: code checkout
        uses: easingthemes/ssh-deploy@v4.1.8
        env:
          SSH_PRIVATE_KEY: ${{ secrets.AWS_PRIVATE_KEY }}
          REMOTE_HOST: ${{ secrets.AWS_HOST }}
          REMOTE_USER: ${{ secrets.AWS_USER }}
          SOURCE: "./"
          TARGET: ${{ secrets.AWS_TARGET_FOLDER }}
        
      
  deploy:
    runs-on: ubuntu-latest
    needs: build
    
    steps:
      - name: Configure SSH
        run: |
          mkdir -p ~/.ssh/
          echo "$SSH_KEY" > ~/.ssh/engageathlete.key
          chmod 600 ~/.ssh/engageathlete.key
          cat >>~/.ssh/config <<END
          Host staging
            HostName $SSH_HOST
            User $SSH_USER
            IdentityFile ~/.ssh/engageathlete.key
            StrictHostKeyChecking no
          END
        env:
          SSH_USER: ${{ secrets.AWS_USER }}
          SSH_KEY: ${{ secrets.AWS_PRIVATE_KEY }}
          SSH_HOST: ${{ secrets.AWS_HOST }}
      - name: Build and Run App
        run: |
          ssh staging 'cd /home/ec2-user/sample/application; \
                       pm2 stop sample || true ; \
                       pm2 delete sample || true ; \
                       pm2 start /home/ec2-user/sample/run/sample.sh --name sample'
